import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';
import { getIdsForVote } from '../utils/getIdsForVote';
import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
  const [ids, updateIds] = useState(() => getIdsForVote());
  const [first, second] = ids;
  console.log(first, second);

  const catPics = trpc.useQuery(['catpic.getTwo', { first, second }]);
  const voteMutation = trpc.useMutation(['catpic.vote']);

  if (!(catPics && catPics.data && catPics.data[0] && catPics.data[1]))
    return <div>{JSON.stringify(catPics)}</div>;

  function vote(selected: number) {
    if (selected === first) {
      voteMutation.mutate({ votedForId: first, votedAgainstId: second });
    } else {
      voteMutation.mutate({ votedForId: second, votedAgainstId: first });
    }

    updateIds(getIdsForVote());
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex flex-col gap-4 items-center justify-center w-1/2 min-h-screen mx-auto'>
        <Image
          style={{ imageRendering: 'pixelated' }}
          src='/img/cats-header.png'
          alt='Cats Header'
          width={305}
          height={85}
        />
        <h1 className='text-5xl font-bold text-red-600'>Which cat is cuter?</h1>
        <div className='flex gap-4'>
          <div className='flex flex-col gap-4 items-center p-4 bg-green-500 rounded-lg'>
            <div className='flex items-center justify-center w-96 h-96 bg-transparent rounded-md overflow-hidden'>
              <img
                className='object-contain max-h-96 max-w-96 rounded-md'
                src={catPics.data[0].imageUrl}
                alt='Cat Picture 1'
              />
            </div>
            <button className='bg-yellow-300 hover:bg-yellow-400 text-xl text-yellow-800 font-bold py-2 px-4 rounded'>
              Pick me!
            </button>
          </div>
          <div className='flex flex-col gap-4 items-center p-4 bg-green-500 rounded-lg'>
            <div className='flex items-center justify-center w-96 h-96 bg-transparent rounded-md overflow-hidden'>
              <img
                className='object-contain max-h-96 max-w-96 rounded-md'
                src={catPics.data[1].imageUrl}
                alt='Cat Picture 2'
              />
            </div>
            <button className='bg-yellow-300 hover:bg-yellow-400 text-xl text-yellow-800 font-bold py-2 px-4 rounded'>
              Noooo pick me!
            </button>
          </div>
        </div>
        <span className='flex gap-2 text-sky-600 font-bold'>
          <Link href='/top10'>
            <a>Cutest Cats</a>
          </Link>
          <span className='font-light'>/</span>
          <Link href='/about'>
            <a>About</a>
          </Link>
        </span>
      </div>
    </>
  );
};

export default Home;
