import type { NextPage } from 'next';
import Head from 'next/head';
import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
  const catPics = trpc.useQuery(['catpic.getTwo']);

  if (!(catPics && catPics.data && catPics.data[0] && catPics.data[1]))
    return <div>{JSON.stringify(catPics)}</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex flex-col items-center justify-center w-1/2 min-h-screen mx-auto'>
        <h1 className='text-2xl'>Which cat is cuter?</h1>
        <div className='flex'>
          <div>
            <img src={catPics.data[0].imageUrl} alt='pic1' />
            <button className='border border-black p-2 shadow-black shadow-sm'>
              Pick me!
            </button>
          </div>
          <div>or</div>
          <div>
            <img src={catPics.data[1]?.imageUrl} alt='pic2' />
            <button className='border border-black p-2 shadow-black shadow-sm'>
              No pick me!
            </button>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
